name: pkart
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  iconsax_flutter: ^1.0.0



  
  
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/onboarding_images/
    - assets/logos/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
